language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - sudo apt-get update
  - sudo apt-get install php5-fpm
  - composer self-update
  - composer install --dev --prefer-source --no-interaction --no-progress

script: vendor/bin/phpunit

branches:
  only:
    - master
    - develop
