language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

branches:
  only:
    - master
    - develop

before_script:
  - sudo apt-get install -y php5-fpm
  - composer self-update --no-interaction
  - composer update --dev --prefer-source $PREFER_LOWEST --no-interaction --no-progress

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
