language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

# Enforces using the container based infrastructure, but I need sudo ...
#sudo: false

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

branches:
  only:
    - master
    - develop

# Currently does not work because of "sudo"
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# Needs to be whitelisted (which it isn't)
#addons:
#  apt_packages:
#  - php5-fpm

before_install:
  - travis_retry sudo apt-get update
  - travis_retry composer self-update --no-interaction

install:
  - travis_retry sudo apt-get install -y php5-fpm
  - travis_retry composer update --dev --prefer-dist $PREFER_LOWEST --no-interaction --no-progress

script: vendor/bin/phpunit --enforce-time-limit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
